In [155]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df1 = pd.read_csv('../dataset/raw/regular_season_box_scores_2010_2024_part_1.csv')
df2 = pd.read_csv('../dataset/raw/regular_season_box_scores_2010_2024_part_2.csv')
df3 = pd.read_csv('../dataset/raw/regular_season_box_scores_2010_2024_part_3.csv')
df4 = pd.read_csv('../dataset/raw/regular_season_totals_2010_2024.csv')

df = pd.concat([df1, df2, df3], axis = 0)

df = df.drop(columns = ['jerseyNum', 'comment'], axis = 1)
df['position'] = df.groupby('personName')['position'].transform(lambda x: x.ffill().bfill())
df = df.dropna()
df['minutes'] = df['minutes'].astype(str)
df['minutes'] = df['minutes'].apply(lambda x: int(x.split(':')[0]) + (int(x.split(':')[1])/60))
selection = df4[['GAME_ID', 'WL', 'TEAM_ABBREVIATION']].copy()
selection = selection.rename({'GAME_ID' : 'gameId', 'TEAM_ABBREVIATION' : 'teamTricode'}, axis = 1)
df = pd.merge(df, selection, on = ['gameId', 'teamTricode'])
df

C:\Users\sidne\AppData\Local\Temp\ipykernel_16288\2848940444.py:13: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['position'] = df.groupby('personName')['position'].transform(lambda x: x.ffill().bfill())

,season_year,game_date,gameId,matchup,teamId,teamCity,teamName,teamTricode,teamSlug,personId,...,reboundsDefensive,reboundsTotal,assists,steals,blocks,turnovers,foulsPersonal,points,plusMinusPoints,WL
0,2010-11,2010-11-10,21000112,NJN @ CLE,1610612751,New Jersey,Nets,NJN,nets,693,...,0,0,0,0,0,0,0,0,-4,W
1,2010-11,2010-10-29,21000020,NJN vs. SAC,1610612751,New Jersey,Nets,NJN,nets,693,...,1,1,1,0,0,1,1,2,6,W
2,2010-11,2010-10-31,21000040,NJN vs. MIA,1610612751,New Jersey,Nets,NJN,nets,693,...,0,1,0,0,0,1,1,0,-8,L
3,2010-11,2010-10-27,21000005,NJN vs. DET,1610612751,New Jersey,Nets,NJN,nets,693,...,1,1,0,0,0,0,1,0,-1,W
4,2011-12,2012-03-16,21100644,NJN @ ORL,1610612751,New Jersey,Nets,NJN,nets,2052,...,3,4,1,1,0,1,1,11,-10,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342429,2023-24,2024-04-02,22301095,WAS vs. MIL,1610612764,Washington,Wizards,WAS,wizards,1641774,...,6,7,3,1,0,1,4,14,6,W
342430,2023-24,2024-04-12,22301172,WAS vs. CHI,1610612764,Washington,Wizards,WAS,wizards,1641774,...,1,1,1,1,1,3,4,19,10,L
342431,2023-24,2024-03-31,22301081,WAS vs. MIA,1610612764,Washington,Wizards,WAS,wizards,1641774,...,2,2,2,0,0,0,3,3,4,L
342432,2023-24,2024-01-25,22300628,WAS vs. UTA,1610612764,Washington,Wizards,WAS,wizards,1641998,...,1,1,0,0,0,0,0,0,0,L
342433,2023-24,2024-01-24,22300620,WAS vs. MIN,1610612764,Washington,Wizards,WAS,wizards,1641998,...,0,0,0,0,0,1,0,0,3,L

In [150]:
player_stats = df.drop(columns = ['game_date', 'gameId', 'matchup', 'teamId', 'teamCity', 'teamTricode', 'teamSlug', 'personId'], axis = 1).copy()
player_stats = player_stats.groupby(by = ['personName', 'teamName', 'season_year', 'position', 'WL']).mean(numeric_only=True).reset_index()
player_stats['fieldGoalsPercentage'] = player_stats.apply(lambda x: (x['fieldGoalsMade'] / x['fieldGoalsAttempted']) * 100 if x['fieldGoalsAttempted'] != 0 else 0, axis = 1)
player_stats['threePointersPercentage'] = player_stats.apply(lambda x: (x['threePointersMade'] / x['threePointersAttempted']) * 100 if x['threePointersAttempted'] != 0 else 0, axis = 1)
player_stats['freeThrowsPercentage'] = player_stats.apply(lambda x: (x['freeThrowsMade'] / x['freeThrowsAttempted']) * 100 if x['freeThrowsAttempted'] != 0 else 0, axis = 1)
dummies = pd.get_dummies(player_stats['WL'])

df_dummies = player_stats.join(dummies)
df_dummies.drop('WL', axis=1)

win_minutes_relation = df_dummies.drop(df_dummies[player_stats.WL == 'L'].index).groupby('personName').sum().reset_index()[['personName', 'W', 'minutes']]
#win_minutes_relation.to_csv('../dataset/clean/win_minutes_relation.csv', index = False)
#player_stats.to_csv('../dataset/clean/stats_by_player.csv', index = False)

            personName   W     minutes
42      Andre Iguodala  21  568.810291
253        Danny Green  21  471.068062
336     Draymond Green  21  589.191608
376        Evan Turner  21  564.375992
393     Garrett Temple  21  394.327438
518      James Johnson  21  381.437785
700      Kent Bazemore  21  424.482795
711         Kevin Love  21  606.832622
739        Kyle Korver  21  511.930541
756    Larry Nance Jr.  21  500.030613
810  Marcus Morris Sr.  21  533.453735
944        P.J. Tucker  21  588.902823
960        Paul George  21  665.421359