In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import statsmodels.api as sm

df = pd.read_csv('../dataset/clean/stats_by_player.csv')

df_c = df[df['position'].str.count('C') > 0]
df_g = df[df['position'].str.count('G') > 0]
df_f = df[df['position'].str.count('F') > 0]

c_features = ['freeThrowsMade', 'reboundsDefensive', 'reboundsOffensive', 'blocks']

g_features = ['threePointersAttempted', 'assists', 'steals', 'turnovers']

f_features = ['threePointersAttempted', 'reboundsDefensive', 'steals', 'turnovers']

palyer_id_columns = ['personName', 'teamName', 'season_year', 'position']

df_c = df_c[palyer_id_columns + c_features]

df_g = df_g[palyer_id_columns + g_features]

df_f = df_f[palyer_id_columns + f_features]

min_max_scaler = preprocessing.MinMaxScaler()
scaled = min_max_scaler.fit_transform(df_c[c_features].values)

min_max_scaler2 = preprocessing.MinMaxScaler()
scaled2 = min_max_scaler.fit_transform(df_g[g_features].values)

min_max_scaler3 = preprocessing.MinMaxScaler()
scaled3 = min_max_scaler.fit_transform(df_f[f_features].values)

df_c[c_features] = scaled

df_g[g_features] = scaled2

df_f[f_features] = scaled3

In [54]:
df_c

,personName,teamName,season_year,position,freeThrowsMade,reboundsDefensive,reboundsOffensive,blocks
35,Aaron Gordon,Nuggets,2023-24,C,0.090909,0.562500,0.500000,1.000000
37,Aaron Gray,Hornets,2010-11,C,0.037694,0.170732,0.179878,0.073171
38,Aaron Gray,Kings,2013-14,C,0.027548,0.121212,0.147727,0.060606
39,Aaron Gray,Raptors,2011-12,C,0.046382,0.252551,0.211735,0.086735
40,Aaron Gray,Raptors,2012-13,C,0.049784,0.126488,0.142857,0.029762
...,...,...,...,...,...,...,...,...
9904,Zeke Nnaji,Nuggets,2020-21,C,0.014545,0.050000,0.045000,0.010000
9906,Zeke Nnaji,Nuggets,2021-22,C,0.087542,0.131944,0.180556,0.055556
9908,Zeke Nnaji,Nuggets,2022-23,C,0.084848,0.108333,0.141667,0.133333
9910,Zeke Nnaji,Nuggets,2023-24,C,0.053476,0.058824,0.139706,0.147059
9926,Zydrunas Ilgauskas,Heat,2010-11,C,0.045455,0.155382,0.187500,0.201389

In [55]:
df_g

,personName,teamName,season_year,position,threePointersAttempted,assists,steals,turnovers
0,AJ Green,Bucks,2022-23,G,0.227626,0.048352,0.042857,0.036735
1,AJ Green,Bucks,2023-24,G,0.228981,0.041209,0.040179,0.030612
3,AJ Griffin,Hawks,2022-23,G,0.245692,0.084249,0.142857,0.108844
5,AJ Griffin,Hawks,2023-24,G,0.212451,0.000000,0.000000,0.057143
6,AJ Price,Cavaliers,2014-15,G,0.075875,0.090909,0.068182,0.038961
...,...,...,...,...,...,...,...,...
9915,Ziaire Williams,Grizzlies,2021-22,G,0.227626,0.123077,0.050000,0.000000
9917,Ziaire Williams,Grizzlies,2022-23,G,0.189689,0.096154,0.083333,0.178571
9919,Ziaire Williams,Grizzlies,2023-24,G,0.303502,0.097902,0.250000,0.194805
9924,Zoran Dragic,Heat,2014-15,G,0.068288,0.030769,0.050000,0.071429
9925,Zoran Dragic,Suns,2014-15,G,0.063230,0.012821,0.000000,0.000000

In [56]:
df_f

,personName,teamName,season_year,position,threePointersAttempted,reboundsDefensive,steals,turnovers
2,AJ Griffin,Hawks,2022-23,F,0.340463,0.107190,0.147059,0.072829
4,AJ Griffin,Hawks,2023-24,F,0.151515,0.062222,0.016667,0.057143
23,Aaron Gordon,Magic,2014-15,F,0.092843,0.174468,0.111702,0.115502
24,Aaron Gordon,Magic,2015-16,F,0.165289,0.303030,0.191558,0.118738
26,Aaron Gordon,Magic,2016-17,F,0.303797,0.242194,0.205696,0.159132
...,...,...,...,...,...,...,...,...
9918,Ziaire Williams,Grizzlies,2023-24,F,0.329545,0.191667,0.156250,0.182143
9920,Zion Williamson,Pelicans,2019-20,F,0.053030,0.238889,0.166667,0.351190
9921,Zion Williamson,Pelicans,2020-21,F,0.050671,0.299454,0.233607,0.391101
9922,Zion Williamson,Pelicans,2022-23,F,0.059561,0.331034,0.275862,0.487685
9923,Zion Williamson,Pelicans,2023-24,F,0.023377,0.270476,0.271429,0.393878

In [57]:
df_team_win_n_time = pd.read_csv('../dataset/clean/team_time_stats.csv')

df_team_win_n_time

    teamName season_year       minutes  wins
0      76ers     2010-11  19824.350000    41
1      76ers     2011-12  15876.516667    35
2      76ers     2012-13  19755.216667    34
3      76ers     2013-14  19163.350000    19
4      76ers     2014-15  19539.616667    18
..       ...         ...           ...   ...
415  Wizards     2019-20  16830.300000    25
416  Wizards     2020-21  17300.583333    34
417  Wizards     2021-22  19718.600000    35
418  Wizards     2022-23  19460.750000    35
419  Wizards     2023-24  19514.983333    15

[420 rows x 4 columns]

In [58]:
df_player_time = pd.read_csv('../dataset/clean/player_time_stats.csv')

df_player_time

,personName,teamName,season_year,position,mean_minutes_played,total_minutes_played
0,AJ Green,Bucks,2022-23,G,9.855714,344.950000
1,AJ Green,Bucks,2023-24,G,10.969345,614.283333
2,AJ Griffin,Hawks,2022-23,F,19.083660,973.266667
3,AJ Griffin,Hawks,2022-23,G,20.389683,428.183333
4,AJ Griffin,Hawks,2023-24,F,8.998889,134.983333
...,...,...,...,...,...,...
9922,Zion Williamson,Pelicans,2022-23,F,32.968966,956.100000
9923,Zion Williamson,Pelicans,2023-24,F,31.527619,2206.933333
9924,Zoran Dragic,Heat,2014-15,G,6.178333,61.783333
9925,Zoran Dragic,Suns,2014-15,G,2.238889,13.433333
9926,Zydrunas Ilgauskas,Heat,2010-11,C,15.907870,1145.366667

In [59]:
time_n_win_stats = pd.merge(df_player_time, df_team_win_n_tim mplayer_win_participation

              personName  teamName season_year position  win_participation
0               AJ Green     Bucks     2022-23        G           1.008917
1               AJ Green     Bucks     2023-24        G           2.544839
2             AJ Griffin     Hawks     2022-23        F           2.773706
3             AJ Griffin     Hawks     2022-23        G           6.939091
4             AJ Griffin     Hawks     2023-24        F           1.951051
...                  ...       ...         ...      ...                ...
9922     Zion Williamson  Pelicans     2022-23        F           1.026551
9923     Zion Williamson  Pelicans     2023-24        F           0.105356
9924        Zoran Dragic      Heat     2014-15        G           1.704864
9925        Zoran Dragic      Suns     2014-15        G           0.029610
9926  Zydrunas Ilgauskas      Heat     2010-11        C           1.200293

[9927 rows x 5 columns]

In [60]:
df_c = pd.merge(df_c, player_win_participation, on=palyer_id_columns, how='inner')

df_g = pd.merge(df_g, player_win_participation, on=palyer_id_columns, how='inner')

df_f = pd.merge(df_f, player_win_participation, on=palyer_id_columns, how='inner')

In [62]:
X = df_c[c_features]
Y = df_c[['win_participation']]

X_sm = sm.add_constant(X) 
modelo_stats = sm.OLS(Y, X_sm).fit()

modelo_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      win_participation   R-squared:                       0.003
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     1.619
Date:                Thu, 19 Jun 2025   Prob (F-statistic):              0.167
Time:                        18:07:01   Log-Likelihood:                -4090.4
No. Observations:                2053   AIC:                             8191.
Df Residuals:                    2048   BIC:                             8219.
Df Model:                           4
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
const                 1.5598      0.080     19.401      0.000       1.402       1.718
freeThrowsMade       -0.4201      0.406     -1.034      0.301      -1.217       0.376
reboundsDefensive     0.9379      0.432      2.170      0.030       0.090       1.786
reboundsOffensive     0.0300      0.410      0.073      0.942      -0.774       0.834
blocks               -0.3485      0.315     -1.106      0.269      -0.966       0.269
==============================================================================
Omnibus:                      441.689   Durbin-Watson:                   1.893
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              785.422
Skew:                           1.369   Prob(JB):                    2.80e-171
Kurtosis:                       4.297   Cond. No.                         14.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [63]:
X = df_g[g_features]
Y = df_g[['win_participation']]

X_sm = sm.add_constant(X) 
modelo_stats = sm.OLS(Y, X_sm).fit()

modelo_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      win_participation   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.8560
Date:                Thu, 19 Jun 2025   Prob (F-statistic):              0.490
Time:                        18:11:25   Log-Likelihood:                -7404.7
No. Observations:                3687   AIC:                         1.482e+04
Df Residuals:                    3682   BIC:                         1.485e+04
Df Model:                           4
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                      1.7293      0.063     27.536      0.000       1.606       1.852
threePointersAttempted     0.1413      0.212      0.665      0.506      -0.275       0.558
assists                    0.4099      0.324      1.264      0.206      -0.226       1.046
steals                    -0.4216      0.307     -1.375      0.169      -1.023       0.179
turnovers                 -0.3917      0.422     -0.928      0.354      -1.220       0.436
==============================================================================
Omnibus:                      792.673   Durbin-Watson:                   1.873
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1431.639
Skew:                           1.366   Prob(JB):                    1.33e-311
Kurtosis:                       4.362   Cond. No.                         18.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [64]:
X = df_f[f_features]
Y = df_f[['win_participation']]

X_sm = sm.add_constant(X) 
modelo_stats = sm.OLS(Y, X_sm).fit()

modelo_stats.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      win_participation   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.4689
Date:                Thu, 19 Jun 2025   Prob (F-statistic):              0.759
Time:                        18:11:27   Log-Likelihood:                -8450.5
No. Observations:                4187   AIC:                         1.691e+04
Df Residuals:                    4182   BIC:                         1.694e+04
Df Model:                           4
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                      1.7307      0.061     28.175      0.000       1.610       1.851
threePointersAttempted     0.0570      0.168      0.340      0.734      -0.272       0.386
reboundsDefensive         -0.1549      0.323     -0.479      0.632      -0.789       0.479
steals                    -0.1301      0.298     -0.436      0.663      -0.715       0.455
turnovers                 -0.1569      0.364     -0.431      0.666      -0.870       0.556
==============================================================================
Omnibus:                      960.205   Durbin-Watson:                   1.849
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1811.758
Skew:                           1.425   Prob(JB):                         0.00
Kurtosis:                       4.505   Cond. No.                         16.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""