In [224]:
import pandas as pd
import numpy as np

In [225]:
df1 = pd.read_csv('../dataset/raw/regular_season_box_scores_2010_2024_part_1.csv')
df2 = pd.read_csv('../dataset/raw/regular_season_box_scores_2010_2024_part_2.csv')
df3 = pd.read_csv('../dataset/raw/regular_season_box_scores_2010_2024_part_3.csv')
df4 = pd.read_csv('../dataset/raw/regular_season_totals_2010_2024.csv')

df = pd.concat([df1, df2, df3], axis = 0)
df.dropna()
def convert_minutes(x):
    if pd.isna(x):
        return None
    try:
        minutes, seconds = map(int, x.split(':'))
        return minutes + seconds / 60
    except:
        return None

df['minutes'] = df['minutes'].apply(convert_minutes)
team_df = pd.read_csv('../dataset/raw/regular_season_totals_2010_2024.csv')
player_anomaly = pd.read_csv('../dataset/clean/players_with_anomaly.csv')

In [226]:
team_df_sorted = team_df.sort_values(by='GAME_ID')

merged = team_df_sorted.merge(
    team_df_sorted,
    on='GAME_ID',
    suffixes=('', '_opponent')
)
merged = merged[merged['TEAM_ID'] != merged['TEAM_ID_opponent']]

merged['PLUS_MINUS'] = merged['PTS'] - merged['PTS_opponent']

result = merged[['GAME_ID', 'PTS', 'PTS_opponent', 'PLUS_MINUS']]
result.rename(columns={'GAME_ID': 'gameId'}, inplace=True)

new_df = df.merge(result, on = 'gameId')
new_anomaly = player_anomaly.merge(result, on = 'gameId')
new_anomaly

C:\Users\sidne\AppData\Local\Temp\ipykernel_3032\2099643678.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.rename(columns={'GAME_ID': 'gameId'}, inplace=True)

,Unnamed: 0,personName,gameId,minutes,fieldGoalsMade,fieldGoalsAttempted,fieldGoalsPercentage,threePointersMade,threePointersAttempted,threePointersPercentage,...,anomaly_flag,season_year,game_date,position,personId,teamId,seasonMeanMinutes,PTS,PTS_opponent,PLUS_MINUS
0,0,Tyler Johnson,21400625,0.0,0,0,0.0,0,0,0.0,...,-1,2014-15,2015-01-21,NaN,204020,1610612748,18.844271,78,76,2
1,0,Tyler Johnson,21400625,0.0,0,0,0.0,0,0,0.0,...,-1,2014-15,2015-01-21,NaN,204020,1610612748,18.844271,76,78,-2
2,1,Tyler Johnson,21400625,0.0,0,0,0.0,0,0,0.0,...,-1,2014-15,2015-01-21,NaN,204020,1610612748,18.844271,78,76,2
3,1,Tyler Johnson,21400625,0.0,0,0,0.0,0,0,0.0,...,-1,2014-15,2015-01-21,NaN,204020,1610612748,18.844271,76,78,-2
4,2,Tyler Johnson,21400625,0.0,0,0,0.0,0,0,0.0,...,-1,2014-15,2015-01-21,NaN,204020,1610612748,18.844271,78,76,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387015,193507,Zylan Cheatham,22100665,0.0,0,0,0.0,0,0,0.0,...,-1,2021-22,2022-01-17,NaN,1629597,1610612762,5.183333,101,95,6
387016,193508,Zylan Cheatham,22100665,0.0,0,0,0.0,0,0,0.0,...,-1,2021-22,2022-01-17,NaN,1629597,1610612748,NaN,95,101,-6
387017,193508,Zylan Cheatham,22100665,0.0,0,0,0.0,0,0,0.0,...,-1,2021-22,2022-01-17,NaN,1629597,1610612748,NaN,101,95,6
387018,193509,Zylan Cheatham,22100665,0.0,0,0,0.0,0,0,0.0,...,-1,2021-22,2022-01-17,NaN,1629597,1610612762,5.183333,95,101,-6
387019,193509,Zylan Cheatham,22100665,0.0,0,0,0.0,0,0,0.0,...,-1,2021-22,2022-01-17,NaN,1629597,1610612762,5.183333,101,95,6

In [227]:
league_ppp = 1.08  # substitua se tiver valor exato
team_pace = 100    # substitua com valor real
league_pace = 100  # substitua com valor real

new_anomaly['offensive_possessions'] = (
    new_anomaly['fieldGoalsAttempted'] +
    0.44 * new_anomaly['freeThrowsAttempted'] +
    new_anomaly['turnovers'] -
    new_anomaly['reboundsOffensive']
)

new_anomaly['points_produced'] = new_anomaly['points'] + 0.5 * new_anomaly['assists']
new_anomaly['marginal_offense'] = (
    new_anomaly['points_produced'] - 0.92 * league_ppp * new_anomaly['offensive_possessions']
)
marginal_points_per_win = 0.32 * 100 * (team_pace / league_pace)
new_anomaly['OWS'] = new_anomaly['marginal_offense'] / marginal_points_per_win

In [228]:
new_anomaly['defensive_rating'] = 106  # ou use real por jogador

new_anomaly['team_minutes'] = 5 * 48  # 5 jogadores * 48 min
new_anomaly['team_def_possessions'] = new_anomaly['team_minutes']  # aproximação simplificada

new_anomaly['marginal_defense'] = (
    (new_anomaly['minutes'] / new_anomaly['team_minutes']) *
    new_anomaly['team_def_possessions'] *
    (1.08 * league_ppp - new_anomaly['defensive_rating'] / 100)
)

new_anomaly['marginal_points_per_win'] = 0.32 * league_ppp * 100 * (team_pace / league_pace)

new_anomaly['DWS'] = new_anomaly['marginal_defense'] / new_anomaly['marginal_points_per_win']
new_anomaly['WS'] = new_anomaly['DWS']+new_anomaly['OWS']

new_anomaly['DWS'] = new_anomaly['DWS'].replace(0, np.nan)
new_anomaly = new_anomaly.dropna()
new_anomaly['WS'] = new_anomaly['DWS']+new_anomaly['OWS']

In [229]:
league_ppp = 1.08  # substitua se tiver valor exato
team_pace = 100    # substitua com valor real
league_pace = 100  # substitua com valor real

df['offensive_possessions'] = (
    df['fieldGoalsAttempted'] +
    0.44 * df['freeThrowsAttempted'] +
    df['turnovers'] -
    df['reboundsOffensive']
)

df['points_produced'] = df['points'] + 0.5 * df['assists']
df['marginal_offense'] = (
    df['points_produced'] - 0.92 * league_ppp * df['offensive_possessions']
)
marginal_points_per_win = 0.32 * 100 * (team_pace / league_pace)
df['OWS'] = df['marginal_offense'] / marginal_points_per_win

df['defensive_rating'] = 106  # ou use real por jogador

df['team_minutes'] = 5 * 48  # 5 jogadores * 48 min
df['team_def_possessions'] = df['team_minutes']  # aproximação simplificada

df['marginal_defense'] = (
    (df['minutes'] / df['team_minutes']) *
    df['team_def_possessions'] *
    (1.08 * league_ppp - df['defensive_rating'] / 100)
)

df['marginal_points_per_win'] = 0.32 * league_ppp * 100 * (team_pace / league_pace)

df['DWS'] = df['marginal_defense'] / df['marginal_points_per_win']
df['WS'] = df['DWS']+df['OWS']

In [230]:
#new_anomaly.to_csv('../dataset/clean/new_anomaly_with_winshare.csv')

In [281]:
top20 = new_anomaly.groupby(by = 'gameId').first().sort_values(by = 'WS', ascending = False).reset_index()
top20_g = top20[(top20['position'] == 'G') & (top20['season_year'] == '2022-23')].drop_duplicates(subset='personName', keep='first')
top20_f = top20[(top20['position'] == 'F') & (top20['season_year'] == '2022-23')].drop_duplicates(subset='personName', keep='first')
top20_c = top20[(top20['position'] == 'C') & (top20['season_year'] == '2022-23')].drop_duplicates(subset='personName', keep='first')
player_name = list(top20[top20['season_year'] == '2022-23']['personName'])
main_columns = top20[['teamId', 'PLUS_MINUS', 'gameId']]

In [291]:
grouped_season = df.groupby(by = ['season_year', 'personName']).mean(numeric_only = True).sort_values(by = 'WS', ascending = False).reset_index()
only_with_anomaly = grouped_season[grouped_season['personName'].isin(player_name)]
only_with_anomaly = only_with_anomaly.sort_values(by = 'WS', ascending = False)[only_with_anomaly['season_year'] == '2022-23']
only_with_anomaly.head(3)

,season_year,personName,gameId,teamId,personId,jerseyNum,minutes,fieldGoalsMade,fieldGoalsAttempted,fieldGoalsPercentage,...,points_produced,marginal_offense,OWS,defensive_rating,team_minutes,team_def_possessions,marginal_defense,marginal_points_per_win,DWS,WS
358,2022-23,Walker Kessler,2.220058e+07,1.610613e+09,1631117.0,NaN,23.016667,4.027027,5.594595,0.694135,...,9.641892,5.466624,0.170832,106.0,240.0,240.0,2.448973,34.56,0.070861,0.241693
456,2022-23,Wendell Carter Jr.,2.220064e+07,1.610613e+09,1628976.0,NaN,29.641813,5.366667,10.216667,0.493217,...,15.566667,4.226379,0.132074,106.0,240.0,240.0,3.153889,34.56,0.091258,0.230284
1331,2022-23,Zach Collins,2.220065e+07,1.610613e+09,1628380.0,NaN,22.866667,4.238806,8.179104,0.505672,...,12.253731,3.007616,0.093988,106.0,240.0,240.0,2.433013,34.56,0.070400,0.170355

In [302]:
teste = df.merge(main_columns, on = ['teamId', 'gameId'])
player_names = top20_c['personName'].head(20).tolist()

for player in player_names:
    player_stat = teste[(teste['personName'] == player) & (teste['season_year'] == '2022-23')]
    jogos_que_o_time_tem_anomalia = top20[(top20['anomaly_flag'] == -1) & (top20['personName'] == player)]['PLUS_MINUS'].mean()
    jogos_que_nao_tem_anomalia = player_stat[player_stat['season_year'] == '2022-23']['PLUS_MINUS'].mean()
    print(f"o jogador {player} tem jogos que tem anomalia plus-minus: {jogos_que_o_time_tem_anomalia} e jogos que não tem anomalia plus-minus: {jogos_que_nao_tem_anomalia}")

o jogador Xavier Tillman tem jogos que tem anomalia plus-minus: 0.8518518518518519 e jogos que não tem anomalia plus-minus: 1.2280701754385965
o jogador Udoka Azubuike tem jogos que tem anomalia plus-minus: -0.7096774193548387 e jogos que não tem anomalia plus-minus: 0.9344262295081968
o jogador Willy Hernangomez tem jogos que tem anomalia plus-minus: -2.1396396396396398 e jogos que não tem anomalia plus-minus: -2.6595744680851063
o jogador Vince Williams Jr. tem jogos que tem anomalia plus-minus: -3.103448275862069 e jogos que não tem anomalia plus-minus: 1.5
o jogador Vit Krejci tem jogos que tem anomalia plus-minus: -1.6666666666666667 e jogos que não tem anomalia plus-minus: -1.6388888888888888
o jogador Wesley Matthews tem jogos que tem anomalia plus-minus: -4.576086956521739 e jogos que não tem anomalia plus-minus: -7.5
o jogador Wendell Moore Jr. tem jogos que tem anomalia plus-minus: 0.9504950495049505 e jogos que não tem anomalia plus-minus: 1.489795918367347
o jogador Will Barton tem jogos que tem anomalia plus-minus: 0.44642857142857145 e jogos que não tem anomalia plus-minus: -0.6363636363636364
o jogador Tyrese Martin tem jogos que tem anomalia plus-minus: -2.775 e jogos que não tem anomalia plus-minus: -2.775
o jogador Vernon Carey Jr. tem jogos que tem anomalia plus-minus: 0.9619047619047619 e jogos que não tem anomalia plus-minus: 1.28
o jogador Udonis Haslem tem jogos que tem anomalia plus-minus: -0.7756714060031595 e jogos que não tem anomalia plus-minus: 1.0273972602739727
o jogador Wenyen Gabriel tem jogos que tem anomalia plus-minus: 0.12396694214876033 e jogos que não tem anomalia plus-minus: 2.05
o jogador Vlatko Cancar tem jogos que tem anomalia plus-minus: 2.3053435114503817 e jogos que não tem anomalia plus-minus: 1.5897435897435896
o jogador Xavier Cooks tem jogos que tem anomalia plus-minus: -7.166666666666667 e jogos que não tem anomalia plus-minus: -7.166666666666667
o jogador Wendell Carter Jr. tem jogos que tem anomalia plus-minus: -3.227272727272727 e jogos que não tem anomalia plus-minus: 0.0
o jogador Usman Garuba tem jogos que tem anomalia plus-minus: 1.161764705882353 e jogos que não tem anomalia plus-minus: -2.413793103448276
o jogador Ziaire Williams tem jogos que tem anomalia plus-minus: 5.105263157894737 e jogos que não tem anomalia plus-minus: 2.9375